apiVersion: v1
kind: Secret
metadata:
  name: catalog-api-secret
type: Opaque
stringData:
  ConnectionStrings__Postgres: "Host=postgres;Port=5432;Database=fcg_catalog_db;Username=fcg;Password=fcg_secret"
  Jwt__SecretKey: "your-super-secret-key-that-is-at-least-32-chars!!"
  RabbitMq__Password: "guest"
